name          'alphagov-lumberjack'
version       '0.0.1'
source        'https://github.com/alphagov/puppet-lumberjack'
project_page  'https://github.com/alphagov/puppet-lumberjack'
license       'MIT'
